name: "Workflow Dispatch"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  # call-lint:
  #   name: "Lint"
  #   uses: cheqd/cheqd-node/.github/workflows/lint.yml@main

  call-build:
    name: "Build"
    # needs: call-lint
    uses: cheqd/cheqd-node/.github/workflows/build.yml@main
  

  get-artifact-link:
    name: "Get artifact link"
    runs-on: ubuntu-latest
    needs: call-build

    steps:
      - name: Get Artifact URL
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{github.repository_owner}}/${{github.repository}}/actions/runs/${{github.run_id}}/artifacts
  
  # call-test:
  #   name: "Test"
  #   needs: call-build
  #   uses: cheqd/cheqd-node/.github/workflows/test.yml@main
  #   with:
  #     VERSION: ${{ needs.call-build.outputs.VERSION }}

  # call-release:
  #   name: "Release"
  #   needs: [call-test, call-build]
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   uses: cheqd/cheqd-node/.github/workflows/release.yml@main
  #   with:
  #     RELEASE_VERSION: ${{ needs.call-build.outputs.VERSION }}
